<?php

$eqzones = array(
  array('expansion' => 1, 'zone' => 'airplane'),
  array('expansion' => 1, 'zone' => 'akanon'),
  array('expansion' => 1, 'zone' => 'arena'),
  array('expansion' => 1, 'zone' => 'befallen'),
  array('expansion' => 1, 'zone' => 'beholder'),
  array('expansion' => 1, 'zone' => 'blackburrow'),
  array('expansion' => 1, 'zone' => 'butcher'),
  array('expansion' => 1, 'zone' => 'cauldron'),
  array('expansion' => 1, 'zone' => 'cazicthule'),
  array('expansion' => 1, 'zone' => 'commons'),
  array('expansion' => 1, 'zone' => 'crushbone'),
  array('expansion' => 1, 'zone' => 'cshome'),
  array('expansion' => 1, 'zone' => 'eastkarana'),
  array('expansion' => 1, 'zone' => 'ecommons'),
  array('expansion' => 1, 'zone' => 'erudnext'),
  array('expansion' => 1, 'zone' => 'erudnint'),
  array('expansion' => 1, 'zone' => 'erudsxing'),
  array('expansion' => 1, 'zone' => 'everfrost'),
  array('expansion' => 1, 'zone' => 'fearplane'),
  array('expansion' => 1, 'zone' => 'feerrott'),
  array('expansion' => 1, 'zone' => 'felwithea'),
  array('expansion' => 1, 'zone' => 'felwitheb'),
  array('expansion' => 1, 'zone' => 'freporte'),
  array('expansion' => 1, 'zone' => 'freportn'),
  array('expansion' => 1, 'zone' => 'freportw'),
  array('expansion' => 1, 'zone' => 'gfaydark'),
  array('expansion' => 1, 'zone' => 'gukbottom'),
  array('expansion' => 1, 'zone' => 'grobb'),
  array('expansion' => 1, 'zone' => 'guktop'),
  array('expansion' => 1, 'zone' => 'halas'),
  array('expansion' => 1, 'zone' => 'hateplane'),
  array('expansion' => 1, 'zone' => 'hateplaneb'),
  array('expansion' => 1, 'zone' => 'highkeep'),
  array('expansion' => 1, 'zone' => 'highpass'),
  array('expansion' => 1, 'zone' => 'hole'),
  array('expansion' => 1, 'zone' => 'innothule'),
  array('expansion' => 1, 'zone' => 'jaggedpine'),
  array('expansion' => 1, 'zone' => 'kaladima'),
  array('expansion' => 1, 'zone' => 'kaladimb'),
  array('expansion' => 1, 'zone' => 'kedge'),
  array('expansion' => 1, 'zone' => 'kerraridge'),
  array('expansion' => 1, 'zone' => 'kithicor'),
  array('expansion' => 1, 'zone' => 'lakerathe'),
  array('expansion' => 1, 'zone' => 'lavastorm'),
  array('expansion' => 1, 'zone' => 'lfaydark'),
  array('expansion' => 1, 'zone' => 'mistmoore'),
  array('expansion' => 1, 'zone' => 'misty'),
  array('expansion' => 1, 'zone' => 'najena'),
  array('expansion' => 1, 'zone' => 'nektulos'),
  array('expansion' => 1, 'zone' => 'neriaka'),
  array('expansion' => 1, 'zone' => 'neriakb'),
  array('expansion' => 1, 'zone' => 'neriakc'),
  array('expansion' => 1, 'zone' => 'northkarana'),
  array('expansion' => 1, 'zone' => 'nro'),
  array('expansion' => 1, 'zone' => 'oasis'),
  array('expansion' => 1, 'zone' => 'oggok'),
  array('expansion' => 1, 'zone' => 'oot'),
  array('expansion' => 1, 'zone' => 'paineel'),
  array('expansion' => 1, 'zone' => 'paw'),
  array('expansion' => 1, 'zone' => 'permafrost'),
  array('expansion' => 1, 'zone' => 'qcat'),
  array('expansion' => 1, 'zone' => 'qey2hh1'),
  array('expansion' => 1, 'zone' => 'qeynos'),
  array('expansion' => 1, 'zone' => 'qeynos2'),
  array('expansion' => 1, 'zone' => 'qeytoqrg'),
  array('expansion' => 1, 'zone' => 'qrg'),
  array('expansion' => 1, 'zone' => 'rathemtn'),
  array('expansion' => 1, 'zone' => 'rivervale'),
  array('expansion' => 1, 'zone' => 'runnyeye'),
  array('expansion' => 1, 'zone' => 'soldunga'),
  array('expansion' => 1, 'zone' => 'soldungb'),
  array('expansion' => 1, 'zone' => 'soltemple'),
  array('expansion' => 1, 'zone' => 'southkarana'),
  array('expansion' => 1, 'zone' => 'sro'),
  array('expansion' => 1, 'zone' => 'steamfont'),
  array('expansion' => 1, 'zone' => 'stonebrunt'),
  array('expansion' => 1, 'zone' => 'tox'),
  array('expansion' => 1, 'zone' => 'unrest'),
  array('expansion' => 1, 'zone' => 'tutorialb'),
  array('expansion' => 1, 'zone' => 'tutoriala'),

  array('expansion' => 2, 'zone' => 'burningwood'),
  array('expansion' => 2, 'zone' => 'cabeast'),
  array('expansion' => 2, 'zone' => 'cabwest'),
  array('expansion' => 2, 'zone' => 'charasis'),
  array('expansion' => 2, 'zone' => 'chardok'),
  array('expansion' => 2, 'zone' => 'citymist'),
  array('expansion' => 2, 'zone' => 'dalnir'),
  array('expansion' => 2, 'zone' => 'dreadlands'),
  array('expansion' => 2, 'zone' => 'droga'),
  array('expansion' => 2, 'zone' => 'emeraldjungle'),
  array('expansion' => 2, 'zone' => 'fieldofbone'),
  array('expansion' => 2, 'zone' => 'firiona'),
  array('expansion' => 2, 'zone' => 'frontiermtns'),
  array('expansion' => 2, 'zone' => 'kaesora'),
  array('expansion' => 2, 'zone' => 'karnor'),
  array('expansion' => 2, 'zone' => 'kurn'),
  array('expansion' => 2, 'zone' => 'lakeofillomen'),
  array('expansion' => 2, 'zone' => 'nurga'),
  array('expansion' => 2, 'zone' => 'overthere'),
  array('expansion' => 2, 'zone' => 'sebilis'),
  array('expansion' => 2, 'zone' => 'skyfire'),
  array('expansion' => 2, 'zone' => 'swampofnohope'),
  array('expansion' => 2, 'zone' => 'timorous'),
  array('expansion' => 2, 'zone' => 'trakanon'),
  array('expansion' => 2, 'zone' => 'veeshan'),
  array('expansion' => 2, 'zone' => 'veksar'),
  array('expansion' => 2, 'zone' => 'warrens'),
  array('expansion' => 2, 'zone' => 'warslikswood'),


  array('expansion' => 3, 'zone' => 'cobaltscar'),
  array('expansion' => 3, 'zone' => 'crystal'),
  array('expansion' => 3, 'zone' => 'eastwastes'),
  array('expansion' => 3, 'zone' => 'frozenshadow'),
  array('expansion' => 3, 'zone' => 'greatdivide'),
  array('expansion' => 3, 'zone' => 'growthplane'),
  array('expansion' => 3, 'zone' => 'iceclad'),
  array('expansion' => 3, 'zone' => 'kael'),
  array('expansion' => 3, 'zone' => 'mischiefplane'),
  array('expansion' => 3, 'zone' => 'necropolis'),
  array('expansion' => 3, 'zone' => 'sirens'),
  array('expansion' => 3, 'zone' => 'skyshrine'),
  array('expansion' => 3, 'zone' => 'sleeper'),
  array('expansion' => 3, 'zone' => 'templeveeshan'),
  array('expansion' => 3, 'zone' => 'thurgadina'),
  array('expansion' => 3, 'zone' => 'thurgadinb'),
  array('expansion' => 3, 'zone' => 'velketor'),
  array('expansion' => 3, 'zone' => 'wakening'),
  array('expansion' => 3, 'zone' => 'westwastes'),


  array('expansion' => 4, 'zone' => 'acrylia'),
  array('expansion' => 4, 'zone' => 'akheva'),
  array('expansion' => 4, 'zone' => 'bazaar'),
  array('expansion' => 4, 'zone' => 'dawnshroud'),
  array('expansion' => 4, 'zone' => 'echo'),
  array('expansion' => 4, 'zone' => 'fungusgrove'),
  array('expansion' => 4, 'zone' => 'griegsend'),
  array('expansion' => 4, 'zone' => 'grimling'),
  array('expansion' => 4, 'zone' => 'hollowshade'),
  array('expansion' => 4, 'zone' => 'katta'),
  array('expansion' => 4, 'zone' => 'letalis'),
  array('expansion' => 4, 'zone' => 'maiden'),
  array('expansion' => 4, 'zone' => 'mseru'),
  array('expansion' => 4, 'zone' => 'netherbian'),
  array('expansion' => 4, 'zone' => 'nexus'),
  array('expansion' => 4, 'zone' => 'paludal'),
  array('expansion' => 4, 'zone' => 'scarlet'),
  array('expansion' => 4, 'zone' => 'shadeweaver'),
  array('expansion' => 4, 'zone' => 'shadowhaven'),
  array('expansion' => 4, 'zone' => 'sharvahl'),
  array('expansion' => 4, 'zone' => 'sseru'),
  array('expansion' => 4, 'zone' => 'ssratemple'),
  array('expansion' => 4, 'zone' => 'tenebrous'),
  array('expansion' => 4, 'zone' => 'thedeep'),
  array('expansion' => 4, 'zone' => 'thegrey'),
  array('expansion' => 4, 'zone' => 'twilight'),
  array('expansion' => 4, 'zone' => 'umbral'),
  array('expansion' => 4, 'zone' => 'vexthal'),

  array('expansion' => 5, 'zone' => 'poinnovation'),
  array('expansion' => 5, 'zone' => 'pofire'),
  array('expansion' => 5, 'zone' => 'potactics'),
  array('expansion' => 5, 'zone' => 'poair'),
  array('expansion' => 5, 'zone' => 'hohonora'),
  array('expansion' => 5, 'zone' => 'nightmareb'),
  array('expansion' => 5, 'zone' => 'podisease'),
  array('expansion' => 5, 'zone' => 'pojustice'),
  array('expansion' => 5, 'zone' => 'poknowledge'),
  array('expansion' => 5, 'zone' => 'ponightmare'),
  array('expansion' => 5, 'zone' => 'postorms'),
  array('expansion' => 5, 'zone' => 'potimea'),
  array('expansion' => 5, 'zone' => 'potimeb'),
  array('expansion' => 5, 'zone' => 'potorment'),
  array('expansion' => 5, 'zone' => 'potranquility'),
  array('expansion' => 5, 'zone' => 'povalor'),
  array('expansion' => 5, 'zone' => 'poearthb'),
  array('expansion' => 5, 'zone' => 'powater'),
  array('expansion' => 5, 'zone' => 'codecay'),
  array('expansion' => 5, 'zone' => 'hohonorb'),
  array('expansion' => 5, 'zone' => 'bothunder'),
  array('expansion' => 5, 'zone' => 'solrotower'),
  array('expansion' => 5, 'zone' => 'poeartha'),
  array('expansion' => 5, 'zone' => 'powar'),

  array('expansion' => 6, 'zone' => 'nadox'),
  array('expansion' => 6, 'zone' => 'dulak'),
  array('expansion' => 6, 'zone' => 'gunthak'),
  array('expansion' => 6, 'zone' => 'hatesfury'),
  array('expansion' => 6, 'zone' => 'torgiran'),
  array('expansion' => 6, 'zone' => 'chardokb'),
  array('expansion' => 6, 'zone' => 'soldungc'),


  array('expansion' => 7, 'zone' => 'guka'),
  array('expansion' => 7, 'zone' => 'gukb'),
  array('expansion' => 7, 'zone' => 'gukc'),
  array('expansion' => 7, 'zone' => 'gukd'),
  array('expansion' => 7, 'zone' => 'guke'),
  array('expansion' => 7, 'zone' => 'gukf'),
  array('expansion' => 7, 'zone' => 'gukg'),
  array('expansion' => 7, 'zone' => 'gukh'),
  array('expansion' => 7, 'zone' => 'mira'),
  array('expansion' => 7, 'zone' => 'mirb'),
  array('expansion' => 7, 'zone' => 'mirc'),
  array('expansion' => 7, 'zone' => 'mird'),
  array('expansion' => 7, 'zone' => 'mire'),
  array('expansion' => 7, 'zone' => 'mirf'),
  array('expansion' => 7, 'zone' => 'mirg'),
  array('expansion' => 7, 'zone' => 'mirh'),
  array('expansion' => 7, 'zone' => 'miri'),
  array('expansion' => 7, 'zone' => 'mirj'),
  array('expansion' => 7, 'zone' => 'mmca'),
  array('expansion' => 7, 'zone' => 'mmcb'),
  array('expansion' => 7, 'zone' => 'mmcc'),
  array('expansion' => 7, 'zone' => 'mmcd'),
  array('expansion' => 7, 'zone' => 'mmce'),
  array('expansion' => 7, 'zone' => 'mmcf'),
  array('expansion' => 7, 'zone' => 'mmcg'),
  array('expansion' => 7, 'zone' => 'mmch'),
  array('expansion' => 7, 'zone' => 'mmci'),
  array('expansion' => 7, 'zone' => 'mmcj'),
  array('expansion' => 7, 'zone' => 'ruja'),
  array('expansion' => 7, 'zone' => 'rujb'),
  array('expansion' => 7, 'zone' => 'rujc'),
  array('expansion' => 7, 'zone' => 'rujd'),
  array('expansion' => 7, 'zone' => 'ruje'),
  array('expansion' => 7, 'zone' => 'rujf'),
  array('expansion' => 7, 'zone' => 'rujg'),
  array('expansion' => 7, 'zone' => 'rujh'),
  array('expansion' => 7, 'zone' => 'ruji'),
  array('expansion' => 7, 'zone' => 'rujj'),
  array('expansion' => 7, 'zone' => 'taka'),
  array('expansion' => 7, 'zone' => 'takb'),
  array('expansion' => 7, 'zone' => 'takc'),
  array('expansion' => 7, 'zone' => 'takd'),
  array('expansion' => 7, 'zone' => 'take'),
  array('expansion' => 7, 'zone' => 'takf'),
  array('expansion' => 7, 'zone' => 'takg'),
  array('expansion' => 7, 'zone' => 'takh'),
  array('expansion' => 7, 'zone' => 'taki'),
  array('expansion' => 7, 'zone' => 'takj'),


  array('expansion' => 8, 'zone' => 'abysmal'),
  array('expansion' => 8, 'zone' => 'barindu'),
  array('expansion' => 8, 'zone' => 'ferubi'),
  array('expansion' => 8, 'zone' => 'ikkinz'),
  array('expansion' => 8, 'zone' => 'inktuta'),
  array('expansion' => 8, 'zone' => 'kodtaz'),
  array('expansion' => 8, 'zone' => 'natimbi'),
  array('expansion' => 8, 'zone' => 'nedaria'),
  array('expansion' => 8, 'zone' => 'qinimi'),
  array('expansion' => 8, 'zone' => 'qvic'),
  array('expansion' => 8, 'zone' => 'riwwi'),
  array('expansion' => 8, 'zone' => 'snlair'),
  array('expansion' => 8, 'zone' => 'snpool'),
  array('expansion' => 8, 'zone' => 'snplant'),
  array('expansion' => 8, 'zone' => 'sncrematory'),
  array('expansion' => 8, 'zone' => 'tacvi'),
  array('expansion' => 8, 'zone' => 'tipt'),
  array('expansion' => 8, 'zone' => 'txevu'),
  array('expansion' => 8, 'zone' => 'uqua'),
  array('expansion' => 8, 'zone' => 'vxed'),
  array('expansion' => 8, 'zone' => 'yxtta'),

  array('expansion' => 9, 'zone' => 'anguish'),
  array('expansion' => 9, 'zone' => 'bloodfields'),
  array('expansion' => 9, 'zone' => 'causeway'),
  array('expansion' => 9, 'zone' => 'chambersa'),
  array('expansion' => 9, 'zone' => 'chambersb'),
  array('expansion' => 9, 'zone' => 'chambersc'),
  array('expansion' => 9, 'zone' => 'chambersd'),
  array('expansion' => 9, 'zone' => 'chamberse'),
  array('expansion' => 9, 'zone' => 'chambersf'),
  array('expansion' => 9, 'zone' => 'dranik'),
  array('expansion' => 9, 'zone' => 'dranikhollowsa'),
  array('expansion' => 9, 'zone' => 'dranikhollowsb'),
  array('expansion' => 9, 'zone' => 'dranikhollowsc'),
  array('expansion' => 9, 'zone' => 'draniksscar'),
  array('expansion' => 9, 'zone' => 'harbingers'),
  array('expansion' => 9, 'zone' => 'provinggrounds'),
  array('expansion' => 9, 'zone' => 'riftseekers'),
  array('expansion' => 9, 'zone' => 'shadowrest'),
  array('expansion' => 9, 'zone' => 'wallofslaughter'),

  array('expansion' => 10, 'zone' => 'broodlands'),
  array('expansion' => 10, 'zone' => 'delvea'),
  array('expansion' => 10, 'zone' => 'delveb'),
  array('expansion' => 10, 'zone' => 'guildhall'),
  array('expansion' => 10, 'zone' => 'guildlobby'),
  array('expansion' => 10, 'zone' => 'stillmoona'),
  array('expansion' => 10, 'zone' => 'stillmoonb'),
  array('expansion' => 10, 'zone' => 'thenest'),
  array('expansion' => 10, 'zone' => 'thundercrest'),

  array('expansion' => 11, 'zone' => 'eastkorlach'),
  array('expansion' => 11, 'zone' => 'eastkorlacha'),
  array('expansion' => 11, 'zone' => 'shadowspine'),
  array('expansion' => 11, 'zone' => 'westkorlach'),
  array('expansion' => 11, 'zone' => 'westkorlacha'),
  array('expansion' => 11, 'zone' => 'westkorlachb'),
  array('expansion' => 11, 'zone' => 'westkorlachc'),
  array('expansion' => 11, 'zone' => 'corathus'),
  array('expansion' => 11, 'zone' => 'corathusa'),
  array('expansion' => 11, 'zone' => 'corathusb'),
  array('expansion' => 11, 'zone' => 'illsalin'),
  array('expansion' => 11, 'zone' => 'illsalina'),
  array('expansion' => 11, 'zone' => 'illsalinb'),
  array('expansion' => 11, 'zone' => 'illsalinc'),
  array('expansion' => 11, 'zone' => 'drachnidhive'),
  array('expansion' => 11, 'zone' => 'drachnidhivea'),
  array('expansion' => 11, 'zone' => 'drachnidhiveb'),
  array('expansion' => 11, 'zone' => 'drachnidhivec'),
  array('expansion' => 11, 'zone' => 'dreadspire'),

  array('expansion' => 13, 'zone' => 'crescent'),
  array('expansion' => 13, 'zone' => 'highpasshold')
);

$zoneids = array (
  0 => 'NONE',
  1 => 'qeynos',
  2 => 'qeynos2',
  3 => 'qrg',
  4 => 'qeytoqrg',
  5 => 'highpass',
  6 => 'highkeep',
  8 => 'freportn',
  9 => 'freportw',
 10 => 'freporte',
 11 => 'runnyeye',
 12 => 'qey2hh1',
 13 => 'northkarana',
 14 => 'southkarana',
 15 => 'eastkarana',
 16 => 'beholder',
 17 => 'blackburrow',
 18 => 'paw',
 19 => 'rivervale',
 20 => 'kithicor',
 21 => 'commons',
 22 => 'ecommons',
 23 => 'erudnint',
 24 => 'erudnext',
 25 => 'nektulos',
 26 => 'cshome',
 27 => 'lavastorm',
 28 => 'nektropos',
 29 => 'halas',
 30 => 'everfrost',
 31 => 'soldunga',
 32 => 'soldungb',
 33 => 'misty',
 34 => 'nro',
 35 => 'sro',
 36 => 'befallen',
 37 => 'oasis',
 38 => 'tox',
 39 => 'hole',
 40 => 'neriaka',
 41 => 'neriakb',
 42 => 'neriakc',
 43 => 'neriakd',
 44 => 'najena',
 45 => 'qcat',
 46 => 'innothule',
 47 => 'feerrott',
 48 => 'cazicthule',
 49 => 'oggok',
 50 => 'rathemtn',
 51 => 'lakerathe',
 52 => 'grobb',
 53 => 'aviak',
 54 => 'gfaydark',
 55 => 'akanon',
 56 => 'steamfont',
 57 => 'lfaydark',
 58 => 'crushbone',
 59 => 'mistmoore',
 60 => 'kaladima',
 61 => 'felwithea',
 62 => 'felwitheb',
 63 => 'unrest',
 64 => 'kedge',
 65 => 'guktop',
 66 => 'gukbottom',
 67 => 'kaladimb',
 68 => 'butcher',
 69 => 'oot',
 70 => 'cauldron',
 71 => 'airplane',
 72 => 'fearplane',
 73 => 'permafrost',
 74 => 'kerraridge',
 75 => 'paineel',
 76 => 'hateplane',
 77 => 'arena',
 78 => 'fieldofbone',
 79 => 'warslikswood',
 80 => 'soltemple',
 81 => 'droga',
 82 => 'cabwest',
 83 => 'swampofnohope',
 84 => 'firiona',
 85 => 'lakeofillomen',
 86 => 'dreadlands',
 87 => 'burningwood',
 88 => 'kaesora',
 89 => 'sebilis',
 90 => 'citymist',
 91 => 'skyfire',
 92 => 'frontiermtns',
 93 => 'overthere',
 94 => 'emeraldjungle',
 95 => 'trakanon',
 96 => 'timorous',
 97 => 'kurn',
 98 => 'erudsxing',
100 => 'stonebrunt',
101 => 'warrens',
102 => 'karnor',
103 => 'chardok',
104 => 'dalnir',
105 => 'charasis',
106 => 'cabeast',
107 => 'nurga',
108 => 'veeshan',
109 => 'veksar',
110 => 'iceclad',
111 => 'frozenshadow',
112 => 'velketor',
113 => 'kael',
114 => 'skyshrine',
115 => 'thurgadina',
116 => 'eastwastes',
117 => 'cobaltscar',
118 => 'greatdivide',
119 => 'wakening',
120 => 'westwastes',
121 => 'crystal',
123 => 'necropolis',
124 => 'templeveeshan',
125 => 'sirens',
126 => 'mischiefplane',
127 => 'growthplane',
128 => 'sleeper',
129 => 'thurgadinb',
130 => 'erudsxing2',
150 => 'shadowhaven',
151 => 'bazaar',
152 => 'nexus',
153 => 'echo',
154 => 'acrylia',
155 => 'sharvahl',
156 => 'paludal',
157 => 'fungusgrove',
158 => 'vexthal',
159 => 'sseru',
160 => 'katta',
161 => 'netherbian',
162 => 'ssratemple',
163 => 'griegsend',
164 => 'thedeep',
165 => 'shadeweaver',
166 => 'hollowshade',
167 => 'grimling',
168 => 'mseru',
169 => 'letalis',
170 => 'twilight',
171 => 'thegrey',
172 => 'tenebrous',
173 => 'maiden',
174 => 'dawnshroud',
175 => 'scarlet',
176 => 'umbral',
179 => 'akheva',
180 => 'arena2',
181 => 'jaggedpine',
182 => 'nedaria',
183 => 'tutorial',
184 => 'load',
185 => 'load2',
186 => 'hateplaneb',
187 => 'shadowrest',
188 => 'tutoriala',
189 => 'tutorialb',
190 => 'clz',
200 => 'codecay',
201 => 'pojustice',
202 => 'poknowledge',
203 => 'potranquility',
204 => 'ponightmare',
205 => 'podisease',
206 => 'poinnovation',
207 => 'potorment',
208 => 'povalor',
209 => 'bothunder',
210 => 'postorms',
211 => 'hohonora',
212 => 'solrotower',
213 => 'powar',
214 => 'potactics',
215 => 'poair',
216 => 'powater',
217 => 'pofire',
218 => 'poeartha',
219 => 'potimea',
220 => 'hohonorb',
221 => 'nightmareb',
222 => 'poearthb',
223 => 'potimeb',
224 => 'gunthak',
225 => 'dulak',
226 => 'torgiran',
227 => 'nadox',
228 => 'hatesfury',
229 => 'guka',
230 => 'ruja',
231 => 'taka',
232 => 'mira',
233 => 'mmca',
234 => 'gukb',
235 => 'rujb',
236 => 'takb',
237 => 'mirb',
238 => 'mmcb',
239 => 'gukc',
240 => 'rujc',
241 => 'takc',
242 => 'mirc',
243 => 'mmcc',
244 => 'gukd',
245 => 'rujd',
246 => 'takd',
247 => 'mird',
248 => 'mmcd',
249 => 'guke',
250 => 'ruje',
251 => 'take',
252 => 'mire',
253 => 'mmce',
254 => 'gukf',
255 => 'rujf',
256 => 'takf',
257 => 'mirf',
258 => 'mmcf',
259 => 'gukg',
260 => 'rujg',
261 => 'takg',
262 => 'mirg',
263 => 'mmcg',
264 => 'gukh',
265 => 'rujh',
266 => 'takh',
267 => 'mirh',
268 => 'mmch',
269 => 'ruji',
270 => 'taki',
271 => 'miri',
272 => 'mmci',
273 => 'rujj',
274 => 'takj',
275 => 'mirj',
276 => 'mmcj',
277 => 'chardokb',
278 => 'soldungc',
279 => 'abysmal',
280 => 'natimbi',
281 => 'qinimi',
282 => 'riwwi',
283 => 'barindu',
284 => 'ferubi',
285 => 'snpool',
286 => 'snlair',
287 => 'snplant',
288 => 'sncrematory',
289 => 'tipt',
290 => 'vxed',
291 => 'yxtta',
292 => 'uqua',
293 => 'kodtaz',
294 => 'ikkinz',
295 => 'qvic',
296 => 'inktuta',
297 => 'txevu',
298 => 'tacvi',
299 => 'qvicb',
300 => 'wallofslaughter',
301 => 'bloodfields',
302 => 'draniksscar',
303 => 'causeway',
304 => 'chambersa',
305 => 'chambersb',
306 => 'chambersc',
307 => 'chambersd',
308 => 'chamberse',
309 => 'chambersf',
316 => 'provinggrounds',
317 => 'anguish',
318 => 'dranikhollowsa',
319 => 'dranikhollowsb',
320 => 'dranikhollowsc',
321 => 'dranikhollowsd',
322 => 'dranikhollowse',
323 => 'dranikhollowsf',
324 => 'dranikhollowsg',
325 => 'dranikhollowsh',
326 => 'dranikhollowsi',
327 => 'dranikhollowsj',
328 => 'dranikcatacombsa',
329 => 'dranikcatacombsb',
330 => 'dranikcatacombsc',
331 => 'draniksewersa',
332 => 'draniksewersb',
333 => 'draniksewersc',
334 => 'riftseekers',
335 => 'harbingers',
336 => 'dranik',
337 => 'broodlands',
338 => 'stillmoona',
339 => 'stillmoonb',
340 => 'thundercrest',
341 => 'delvea',
342 => 'delveb',
343 => 'thenest',
344 => 'guildlobby',
345 => 'guildhall',
346 => 'barter',
347 => 'illsalin',
348 => 'illsalina',
349 => 'illsalinb',
350 => 'illsalinc',
351 => 'dreadspire',
354 => 'drachnidhive',
355 => 'drachnidhivea',
356 => 'drachnidhiveb',
357 => 'drachnidhivec',
358 => 'westkorlach',
359 => 'westkorlacha',
360 => 'westkorlachb',
361 => 'westkorlachc',
362 => 'eastkorlach',
363 => 'eastkorlacha',
364 => 'shadowspine',
365 => 'corathus',
366 => 'corathusa',
367 => 'corathusb',
368 => 'nektulosa',
369 => 'arcstone',
370 => 'relic',
371 => 'skylance',
372 => 'devastion',
373 => 'devastationa',
374 => 'rage',
375 => 'ragea',
376 => 'takishruins',
377 => 'takishruinsa',
378 => 'elddar',
379 => 'elddara',
380 => 'theater',
381 => 'theatera',
382 => 'freeporteast',
383 => 'freeportwest',
384 => 'freeportsewers',
385 => 'freeportacademy',
386 => 'freeporttemple',
387 => 'freeportmilitia',
388 => 'freeportarena',
389 => 'freeportcityhall',
390 => 'freeporttheater',
391 => 'freeporthall',
392 => 'northro',
393 => 'southro',
394 => 'crescent',
395 => 'moors',
396 => 'stonehive',
397 => 'mesa',
398 => 'roost',
399 => 'steppes',
400 => 'icefall',
401 => 'valdeholm',
402 => 'frostcrypt',
403 => 'sunderock',
404 => 'vergalid',
405 => 'direwind',
406 => 'ashengate',
407 => 'highpasshold',
408 => 'commonlands',
409 => 'oceanoftears',
410 => 'kithforest',
411 => 'befallenb',
412 => 'highpasskeep',
413 => 'innothuleb',
414 => 'toxxulia',
415 => 'mistythicket',
416 => 'kattacastrum',
417 => 'thalassius',
418 => 'atiiki',
419 => 'zhisza',
420 => 'silyssar',
421 => 'solteris',
422 => 'barren',
423 => 'buriedsea',
424 => 'jardelshook',
425 => 'monkeyrock',
426 => 'suncrest',
427 => 'deadbone',
428 => 'blacksail',
429 => 'maidensgrave',
430 => 'redfeather',
431 => 'shipmvp',
432 => 'shipmvu',
433 => 'shippvu',
434 => 'shipuvu',
435 => 'shipmvm',
436 => 'mechanotus',
437 => 'mansion',
438 => 'steamfactory',
439 => 'shipworkshop',
440 => 'gyrospireb',
441 => 'gyrospirez',
442 => 'dragonscale',
443 => 'lopingplains',
444 => 'hillsofshade',
445 => 'bloodmoon',
446 => 'crystallos',
447 => 'guardian',
448 => 'steamfontmts',
449 => 'cryptofshade',
996 => 'arttest',
998 => 'fhalls',
999 => 'apprentice'
);

$zones = array();
foreach ($eqzones as $zone) {
  if ($zone['expansion'] <= $expansion_limit) {
    $zones[] = $zone['zone'];
  }
}
sort ($zones);

?>
