DROP TABLE peq_admin;

CREATE TABLE peq_admin (
id INT(11) auto_increment primary key,
login varchar(30) NOT NULL,
password varchar(255) NOT NULL,
administrator INT(11) NOT NULL DEFAULT '0'
);
INSERT INTO peq_admin VALUES(1, 'admin', '5f4dcc3b5aa765d61d8327deb882cf99', 1);

CREATE TABLE spells (
  spellid int(11) NOT NULL default '0',
  name varchar(64) NOT NULL default '',
  castonyou varchar(120) NOT NULL default '',
  castonother varchar(120) NOT NULL default '',
  fading varchar(120) NOT NULL default '',
  range int(11) NOT NULL default '0',
  aoerange int(11) NOT NULL default '0',
  mana int(11) NOT NULL default '0',
  casttime int(11) NOT NULL default '0',
  recoverytime int(11) NOT NULL default '0',
  recasttime int(11) NOT NULL default '0',
  buffformula int(11) NOT NULL default '0',
  buffduration int(11) NOT NULL default '0',
  aoeduration int(11) NOT NULL default '0',
  targettype int(11) NOT NULL default '0',
  skill int(11) NOT NULL default '0',
  buff1 int(11) NOT NULL default '0',
  buff1val int(11) NOT NULL default '0',
  buff2 int(11) NOT NULL default '0',
  buff2val int(11) NOT NULL default '0',
  buff3 int(11) NOT NULL default '0',
  buff3val int(11) NOT NULL default '0',
  buff4 int(11) NOT NULL default '0',
  buff4val int(11) NOT NULL default '0',
  buff5 int(11) NOT NULL default '0',
  buff5val int(11) NOT NULL default '0',
  buff6 int(11) NOT NULL default '0',
  buff6val int(11) NOT NULL default '0',
  buff7 int(11) NOT NULL default '0',
  buff7val int(11) NOT NULL default '0',
  buff8 int(11) NOT NULL default '0',
  buff8val int(11) NOT NULL default '0',
  buff9 int(11) NOT NULL default '0',
  buff9val int(11) NOT NULL default '0',
  buff10 int(11) NOT NULL default '0',
  buff10val int(11) NOT NULL default '0',
  buff11 int(11) NOT NULL default '0',
  buff11val int(11) NOT NULL default '0',
  buff12 int(11) NOT NULL default '0',
  buff12val int(11) NOT NULL default '0',
  buff1form int(11) NOT NULL default '0',
  buff2form int(11) NOT NULL default '0',
  buff3form int(11) NOT NULL default '0',
  buff4form int(11) NOT NULL default '0',
  buff5form int(11) NOT NULL default '0',
  buff6form int(11) NOT NULL default '0',
  buff7form int(11) NOT NULL default '0',
  buff8form int(11) NOT NULL default '0',
  buff9form int(11) NOT NULL default '0',
  buff10form int(11) NOT NULL default '0',
  buff11form int(11) NOT NULL default '0',
  buff12form int(11) NOT NULL default '0',
  buff1max int(11) NOT NULL default '0',
  buff2max int(11) NOT NULL default '0',
  buff3max int(11) NOT NULL default '0',
  buff4max int(11) NOT NULL default '0',
  buff5max int(11) NOT NULL default '0',
  buff6max int(11) NOT NULL default '0',
  buff7max int(11) NOT NULL default '0',
  buff8max int(11) NOT NULL default '0',
  buff9max int(11) NOT NULL default '0',
  buff10max int(11) NOT NULL default '0',
  buff11max int(11) NOT NULL default '0',
  buff12max int(11) NOT NULL default '0',
  level1 int(4) NOT NULL default '0',
  level2 int(4) NOT NULL default '0',
  level3 int(4) NOT NULL default '0',
  level4 int(4) NOT NULL default '0',
  level5 int(4) NOT NULL default '0',
  level6 int(4) NOT NULL default '0',
  level7 int(4) NOT NULL default '0',
  level8 int(4) NOT NULL default '0',
  level9 int(4) NOT NULL default '0',
  level10 int(4) NOT NULL default '0',
  level11 int(4) NOT NULL default '0',
  level12 int(4) NOT NULL default '0',
  level13 int(4) NOT NULL default '0',
  level14 int(4) NOT NULL default '0',
  level15 int(4) NOT NULL default '0',
  level16 int(4) NOT NULL default '0',
  regent1_id int(11) NOT NULL default '0',
  regent1_count int(11) NOT NULL default '0',
  regent2_id int(11) NOT NULL default '0',
  regent2_count int(11) NOT NULL default '0',
  regent3_id int(11) NOT NULL default '0',
  regent3_count int(11) NOT NULL default '0',
  regent4_id int(11) NOT NULL default '0',
  regent4_count int(11) NOT NULL default '0',
  timeofday int(11) NOT NULL default '0',
  UNIQUE KEY spellid (spellid)
) TYPE=MyISAM;

